/**
 * Complete list of automotive-related words for the Word Hunt Game.
 * All words are used in puzzle generation. The generator will select
 * a subset of words that can fit in the grid while ensuring all selected
 * words are findable.
 */
export const WORD_LIST = [
  "FLUIDS",
  "CHEMICALS",
  "BATTERY",
  "WIPER",
  "SHOCKABSORBER",
  "ALTERNATOR",
  "WHEELBEARING",
  "DRIVEBELT",
  "TIMINGBELT",
  "CVJOINTBOOT",
  "BRAKELIGHTBULB",
  "HEADLIGHTBULB",
  "INTERIORBULB",
  "LICENSEPLATEBULB",
  "PARKLIGHTBULB",
  "THIRDBRAKELIGHTBULB",
  "IGNITIONCOIL",
  "COMPRESSOR",
  "CVJOINT",
  "DRIVESHAFT",
  "RACKEND",
  "TIERODEND",
  "EVAPORATOR",
  "AIRFILTER",
  "CABINAIRFILTER",
  "FUELFILTER",
  "OILFILTER",
  "POLLENFILTER",
  "TRANSMISSIONFILTER",
  "CAMSHAFTCOVERGASKET",
  "BALLJOINT",
  "TAILLIGHTLAMP",
  "STABILIZERLINK",
  "PAGOIL",
  "BRAKEPADS",
  "SPARKPLUG",
  "DRIVEBELTIDLERPULLEY",
  "WATERPUMP",
  "RADIATOR",
  "BRAKEROTOR",
  "OILPANDRAINPLUGSEAL",
  "BRAKESHOE",
  "STARTER",
  "DRIVEBELTTENSIONER",
  "TIMINGBELTSET",
] as const;
